### ISSUE TITLE
Call for recipes

### ISSUE THREAD

**Issue by gadfly361** [reagent-project/reagent-cookbook#1]
Looking for collaborators to add well-documented reagent recipes. 

To contribute, please make a folder with a working example.  Include a README that has the problem defined as well as a detailed solution.  I would prefer clarity over brevity in the solution, especially when displaying code.

Also, let me know if you have any suggestions for future recipes.

**Comment by borkdude** [comment]
+1 for file upload, preferably also a solution that supports IE9 (using iframe transport). I have tried it with Google Closure's iFrameIo, but I'm also curious about a solution with jQuery file upload.

**Comment by gadfly361** [comment]
Anyone interested in making a file upload recipe? :)

**Comment by yogthos** [comment]
[This](https://github.com/yogthos/yuggoth/blob/master/src-cljs/yuggoth/pages/upload.cljs) could be a good starting point, but I don't have time to convert it to a recipe in the near future. :)

**Comment by borkdude** [comment]
Another idea for a recipe: using react-router together with Reagent. It should be possible according to David Nolen... https://twitter.com/borkdude/status/566699230853865474

**Comment by borkdude** [comment]
@yogthos Why didn't I see your yuggoth repo before. It contains several implicit recipes I really can use in my current project! Thanks! :+1:

**Comment by yogthos** [comment]
haha excellent, feel free to extract those into actual recipes if you get a chance :)

**Comment by gadfly361** [comment]
Moving discussion to google groups: https://groups.google.com/forum/#!topic/reagent-project/KW9-HJR9ATA
