### ISSUE TITLE
Request for recipe: Reagent Cursor

### ISSUE THREAD

**Issue by ducky427** [reagent-project/reagent-cookbook#11]
As a user, I've found the documentation around [reagent-cursor](https://github.com/reagent-project/reagent-cursor) project slightly thin. A real world useage would really help.

Thanks!

**Comment by Frozenlock** [comment]
Cursors act like normal atoms. If they are created with a reagent atom, they will act like one.

This means that every recipe here should be valid for a cursor as well.

Take this project I'm working on:
www.graphivac.com

Each diagram is stored as an atom.

It would suck to have to give the grid coordinates as an argument to every subcomponent.
It would pretty quickly devolve into this:
```clj 
[my-cell-component 
                   grid-atom  ;; <--- the reagent atom
                   grid-coord cell-property cell-subproperty...] ;; <-- path to value

;; and now to update a cell?
(swap! grid-atom assoc-in [grid-coord cell-property cell-subproperty...] new-value)
;; *Sad panda*

```

When using cursors, I can just design my cell components to expect the atom directly.

```clj

(let [coord-cursor (rc/cur grid-atom [grid-coord])
;; ...       
;; do some stuff... and then, multiple subcomponents down the line,
;; we can abstract yet another nested path.

       cell-prop-cursor (rc/cur coord-cursor [cell-property cell-subproperty])] ;; <-- cursors are composable




[my-cell-component cell-prop-cursor]  ;; <--- Much cleaner and easier to think about
;; updates from inside this component:
(reset! cell-prop-cursor new-val) ;;<--- don't have to know the nested path.
;; The property path can change without having to change any code in this component.

;; When giving a cursor, you also limit what a component can modify.
;; It cannot see the whole atom, only what's in the cursor.
```

I pretty much said the same thing that's in the reagent-cursor readme...
Could you point out which part should be explained in more details?

**Comment by gadfly361** [comment]
I haven't really used cursors much.  Anyone interested in making a dedicated recipe for showing how to use them? @Frozenlock? @seancorfield?

**Comment by ducky427** [comment]
Looks like `reagent-cursor` has been deprecated. So this issue is now outdated. Will open another if required.
