### ISSUE TITLE
Google Closure instead of jquery

### ISSUE THREAD

**Issue by JulianLeviston** [reagent-project/reagent-cookbook#13]
Most of these examples use jquery. Why not use google closure?

**Comment by gadfly361** [comment]
Hey! jQuery was used because many recipes are referencing examples of how to do something in javascript, and those reference examples use jQuery. 

For example the [draggable](https://github.com/reagent-project/reagent-cookbook/tree/master/recipes/draggable) recipe is based on this [example](http://jqueryui.com/draggable/), which uses jQuery.  Since readers are already having to understand the switch from javascript to clojurescript, I'd prefer not swap out jQuery too.

However, the use of google closure is welcome in new recipes! :)

**Comment by JulianLeviston** [comment]
Sure, having them both is a great idea. I just feel the google closure library is underuitilized, and I don't want to include the WHOLE of jquery just so I can use drag n drop... (or in this case, a vertical reordering functionality).  Also, jquery doesn't allow closure to do dead code elimination, right?

So, I'm building my vertical reordering using the google closure goog.fx.DragListGroup class.

**Comment by gadfly361** [comment]
That makes sense to me. Though for the recipes, I am prioritizing lowering the barrier to entry of using reagent over any kind of optimizations.

I do want to avoid any implicit recommendation like using jQuery though, so I am glad you pointed that out. I am hopeful for more contributions that use other options and keep the cookbook agnostic.

**Comment by JulianLeviston** [comment]
Sure... isn't using jquery just a different barrier?

One of the things I really like about closure is its decided UN-jquery-ness... the problem with jquery is it's kind of a different language to javascript. The functions that sound like higher order functions but actually behave substantially differently are a good example.

But I'll be quiet now :) I really appreciate the work you (and others!) have done and I sound like I'm just whining rather than being thankful.

**Comment by JulianLeviston** [comment]
PHEW... well I finally got an implementation of drag and drop in *one* instance working just now on my project, but man... it's *anything* but straightforward. DragListGroup isn't really meant to be used in this way. It's a pity that it's not more extensible. In the end I had to use a lot of code, and I also had to write a line using the private API, so I don't think I'm going to work on a cookbook for this... one would be better writing one's own implementation of sortable() using the closure API, but I just don't have the time to do that at the moment.

It's designed primarily to make EVERYTHING in an element drag 'n droppable between groups of lists... so shoehorning it into acting like a sortable isn't really that fun, and making it "cancel" its sort isn't part of its API, so I had to write a line of private API code to "reset" it after I'd taken the data out at drop-time.

jQuery is much more approachable and easy...

**Comment by gadfly361** [comment]
Oh, no worries that it didn't work out for the cookbook. I really appreciate the feedback about your experience working with DragListGroup though!

**Comment by JulianLeviston** [comment]
No worries... it's a pity there aren't more pure clojurescript things have this functionality though, because they'd be much nicer than going down to google closure or jquery. Perhaps something along the lines of David Nolen's FRP style code with core.async and drag n drop hooked up to Google closure for the browser independent parts.
