### ISSUE TITLE
NVD3 Recipe: undefined is not a function with NVD3 v1.7.1 and D3 v3.5.5

### ISSUE THREAD

**Issue by anujsrc** [reagent-project/reagent-cookbook#15]
The NVD3 recipe of line chart fails with ``undefined is not a function`` at the last line of this snippet-

```
...
(.addGraph
    js/nv
    (fn []
      (let [chart (.. js/nv -models lineChart
...
```
To reproduce this issue, just bump the version of NVD3 and D3 as shown below-

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
  </head>
  <body>
    <div id="app"> Loading... </div>
    <!-- nvd3 -->
    <script src="//cdnjs.cloudflare.com/ajax/libs/d3/3.5.5/d3.js"></script>
    <link href="//cdnjs.cloudflare.com/ajax/libs/nvd3/1.7.1/nv.d3.css" rel="stylesheet">
    <script src="//cdnjs.cloudflare.com/ajax/libs/nvd3/1.7.1/nv.d3.js"></script>

    <script src="/js/app.js"></script>
  </body>
</html>
```
Now, if you access the demo it will fail with ``Uncaught TypeError: undefined is not a function``. Here are the screenshots that show the error in console and code at the specified line number-

![selection_037](https://cloud.githubusercontent.com/assets/1001682/7500010/b7db3af0-f448-11e4-89c0-2f0dac87c49b.png)
![selection_038](https://cloud.githubusercontent.com/assets/1001682/7500011/b7dd228e-f448-11e4-9f4b-c61bd0918aff.png)

**Comment by gadfly361** [comment]
I was able to reproduce your error.  To investigate, I tried dropping nvd3 down to version 1.6.0 and I saw this warning:

```
lineChart.transitionDuration` has been deprecated.
```

Then I found this [issue](https://github.com/angularjs-nvd3-directives/angularjs-nvd3-directives/issues/210).  The comment by eddiejaoude on March 24 suggests to remove the ```.transitionDuration(350)```.

So if you remove this [line](https://github.com/reagent-project/reagent-cookbook/blob/master/recipes/nvd3/src/cljs/nvd3/core.cljs#ln-14), everything should work.

**Comment by anujsrc** [comment]
Thanks @gadfly361 :+1: That solves the problem.
