### ISSUE TITLE
More minimal templates?

### ISSUE THREAD

**Issue by jellea** [reagent-project/reagent-cookbook#2]
Wow, I love the idea and the examples so far! They are super useful, thank you! Would it be an idea to have more minimal boilerplates around the examples? I get lost every time I dive into a new example and need to click some files/folders to find what I'm searching for. For example routing is only relevant for the routing example, still it's included in every example. Would prefer to see a single cljs file in the root of every example folder showing only the bare minimum solution. Also it would be nice to have some demos ready hosted/included somewhere. I'd be happy to contribute if you need help.

**Comment by jellea** [comment]
Late response, but just wanted to say I like how it is now! :)

**Comment by gadfly361** [comment]
Updated reagent-cookbook-template to make it even more minimal (i.e., removed ring server).
