### ISSUE TITLE
Markdown editor recipe needs to include content in the args to the render fn

### ISSUE THREAD

**Issue by jwhitlark** [reagent-project/reagent-cookbook#25]
(defn markdown-component [content]
      (fn []
        [:div {:dangerouslySetInnerHTML
               {:__html (-> content str js/marked)}}]))

needs to be:

    (defn markdown-component [content]
      (fn [content]
        [:div {:dangerouslySetInnerHTML
               {:__html (-> content str js/marked)}}]))

otherwise only the initial value will be rendered.

**Comment by gadfly361** [comment]
@jwhitlark I just updated the markdown recipe to use the standard reagent-cookbook-template as a starting point. In doing so, I explored your recommendation. However, for me, the markdown updates with every key press with the first code snippet, and doesn't update with the proposed second snippet.

@lacarmen was the original author of this recipe and may have more insight.

**Comment by jwhitlark** [comment]
Odd. I'll double check, perhaps my use varies in an important way. Thanks for looking into it.

**Comment by gadfly361** [comment]
@jwhitlark just wanted to check in and see if there was any update regarding this issue.

**Comment by jwhitlark** [comment]
I'm afraid I don't.  In the use case I had, it needed the argument
specified in the inner fn to work, but that code isn't available to me
anymore.
https://github.com/Day8/re-frame/wiki/Creating%20Reagent%20Components#form-2--a-function-returning-a-function
seems to argue that is the way to do it, but I don't have any deeper
insight ATM.

**Comment by gadfly361** [comment]
@jwhitlark Ahh, I think I may have a guess at the difference now in our use cases. In the recipe, the code snippet you referenced is an intermediate version of the component - the final version ends up looking [like this](https://github.com/reagent-project/reagent-cookbook/blob/master/recipes/markdown-editor/src/cljs/markdown_editor/core.cljs#L18-L26), which is akin to a form-3 (instead of form-2).

**Comment by gadfly361** [comment]
I'll look into updating this recipe to use `create-class` as opposed to `with-meta` to make it more consistent with the other recipes (and with the docs that you referenced).

**Comment by jwhitlark** [comment]
Oh, I see.  Yea, that would do it.  I'd suggest adding a comment to step 5 then, explaining that this is not the final version of that function.  It's easy to miss, esp. if you're comfortable with reagent and just looking for something specific to process markdown.

**Comment by jwhitlark** [comment]
@gadfly361 Either way. (update or comment)

**Comment by gadfly361** [comment]
For sure, that makes sense! Thanks for helping identify this :)

**Comment by gadfly361** [comment]
Just pushed an update to the recipe! Closing this issue; however, feel free to reopen if you think the recipe is still misleading.
