### ISSUE TITLE
Routing with secretary and using dispatch!

### ISSUE THREAD

**Issue by smogg** [reagent-project/reagent-cookbook#31]
In the `add-routing` example we use `defroute` to change `:current-page` when navigating. Then view under `:current-page` is rendered and we've got routing working.
But what if we want to run `secretary/dispatch!` manually (for example, after form submit to redirect to a different page)?
We will be correctly taken to a the page cause of the state change, but address bar in our browser won't change.

I see a few _possible_ solutions:
- changing `window.location` inside `defroute` call, but that change will call `dispatch!` again, thus creating an infinite loop
- using `.pushState` from History Api inside `defroute`. That corrects the url, but routing no longer works afterwards...
- setting `window.location` in place of `dispatch!`

**Comment by gadfly361** [comment]
@smogg Thanks for bringing this up! However, I view handling the address bar as a higher-level concern. There are several options, and I'd rather not include one in the recipe.  Personally, I opt to not use `secretary/dispatch!` and instead change the hash with javascript interop:
