### ISSUE TITLE
File upload recipe

### ISSUE THREAD

**Issue by gosukiwi** [reagent-project/reagent-cookbook#32]
It would be great to have a recipe for (possibly multiple) file upload :smile:

**Comment by gadfly361** [comment]
@gosukiwi I added a recipe called `file-upload`.  I used the service [filestack](https://www.filestack.com/) which appears to be pretty popular and supports s3, dropbox, Azure, etc.

**Comment by gosukiwi** [comment]
Oh wow, thanks a lot! It's great! Originally I ment just a file upload to a local web server though, checking out that solution it seems that they host the files themselves. Maybe I'm mistaken though.

**Comment by gadfly361** [comment]
@gosukiwi Unfortunately, I am not well versed with file uploads. This is a stripped down (and now untested) version of something I have done in the past - it may be more in line with what you wanted:

```clojure
(defn upload-image []
  [:div
   [:iframe {:name  "some-target-name"
             :style {:display "none"}}]
   [:form
    {:method    "post"
     :enc-type  "multipart/form-data"
     :action    "/api/some-endpoint"
     :target    "some-target-name"
     :on-submit #(foobar %)}
    [:input
     {:id   "id-file"
      :type "file"
      :name "id-file"}]
    [:button
     {:id "submit"}
     "Send File"]]])
```

**Comment by gadfly361** [comment]
@gosukiwi Is this issue ok to close or are you still searching for more?

**Comment by gosukiwi** [comment]
Yes, this is ok, you can close it. Thanks a lot for your help! :+1:

**Comment by gadfly361** [comment]
No problem!
