### ISSUE TITLE
file upload example is advertising, not tutorial

### ISSUE THREAD

**Issue by spacejam** [reagent-project/reagent-cookbook#35]
I'd like to see an example of how to open a file and view its contents in cljs. The current recipe is effectively an advertisement for a convoluted paid service, not an example of how to do this relatively simple action.

**Comment by gadfly361** [comment]
@spacejam Thank you for your feedback! I apologize for the confusion; however, the recipe is labeled 'file upload with *filestack*'.

If anyone is up for making an additional recipe for file upload, pull requests are welcomed!
