### ISSUE TITLE
File upload example: callback function?

### ISSUE THREAD

**Issue by bzg** [reagent-project/reagent-cookbook#42]
Thanks for putting these recipes together, that's very useful.

While testing the `file upload` example, I could not figure what callback function to use. My goal is to retrieve the URL of a freshsly uploaded document.

Thanks for any hint!

**Comment by gadfly361** [comment]
@bzg I updated the file-upload recipe to use the new filestack api and to print the url to the console. Please let me know if this helps!

**Comment by bzg** [comment]
Fantastic, thanks a lot for the swift update!

**Comment by gadfly361** [comment]
I am assuming that worked for you, please reopen if it didn't :)

**Comment by bzg** [comment]
Yes, it works fine, thanks again.
