### ISSUE TITLE
reagent-server-rendering puzzle?

### ISSUE THREAD

**Issue by fwchen** [reagent-project/reagent-cookbook#43]
The reagent-server-rendering is different from react server-rendering.

**Comment by gadfly361** [comment]
@fwchen Can you elaborate? I am unclear if this is a comment, a question, or if you are filing an issue with the recipe.

The recipe, which is in a directory called `reagent-server-rendering`, shows how to render reagent on a clojure server.

**Comment by fwchen** [comment]
e..........sorry my english.
react or angular server render render html as browser,  it render once when reload page(F5 or C-R), and link to other page is just ajax(no server render again).
But reagent-server-rendering it just like server template render, every page render is server render.

**Comment by gadfly361** [comment]
@fwchen Ah, I see what you are getting at. The choice to render each page on the server is optional.  You could instead render the initial page on the server, and then use client-side routing with [secretary](https://github.com/gf3/secretary) (or something similar) to avoid rendering each page on the server.

**Comment by fwchen** [comment]
thank you.
