### ISSUE TITLE
Thanks so much for this project!

### ISSUE THREAD

**Issue by ckuttruff** [reagent-project/reagent-cookbook#52]
Sorry, this is not an issue and I can close at end of day, but I just wanted to give y'all a shout out for the great work.

I had fumbled through a few outdated tutorials about handling navigation for reagent, then I stumbled on this:
https://github.com/reagent-project/reagent-cookbook/blob/master/recipes/add-routing/src/cljs/add_routing/core.cljs#L1

Perfect little tutorials in here!  Short, simple, clear, very usable.  Can't tell you how much I appreciate this type of help when learning a bunch of new things at once;  coming back to clojure, new to cljs, service worker, indexed db, structuring things as a single-page app... all super new and interesting and resources like this are invaluable.

THANK YOU!!!

**Comment by ckuttruff** [comment]
lol, ps. I totally submitted a github feature request for "kudos" or something, cause opening an issue is really the only way to get in touch with repo maintainers.  And sometimes "starring" a repo feels grossly insufficient, when good resources and documentation save you hours and make you happy.

to all the contributors here, you have made me happy :)

**Comment by gadfly361** [comment]
@ckuttruff This literally made my day, thanks so much for the kind words!  

TBH, I have neglected this project for a while. Many of this recipes are a couple years old. I should take some time in the next few months to update them and add a batch of new ones. :)

- Matt

---

As an aside, I recommend two leiningen templates for quick starting with reagent: [reagent-figwheel](https://github.com/gadfly361/reagent-figwheel) and [re-frame-template](https://github.com/Day8/re-frame-template).

If you wanted a starter app with routes, you'd just run:

```
lein new reagent-figwheel myapp +routes
```
or
```
lein new re-frame myapp +routes
```

**Comment by ckuttruff** [comment]
@gadfly361 Thanks so much for those tips. Yeah, I def am using figwheel and launched it from a template with reagent.  I haven't done anything with reframe yet, but I am quite pleased with the basic navigation that is now working (amongst other things).  Originally wrote it in sinatra with vuejs, but converted things relatively quickly, cause javascript was driving me mad and I missed clojure :P 

Very much a work in progress, but code so far here:
https://github.com/ckuttruff/orghub
It's gonna use service workers and indexed db wrapper to be a PWA.

Was good motivation to update this project too, which was getting stale with dependencies, etc:
https://github.com/ckuttruff/clj-sql-up/

Was super pleasantly surprised how easy it was to update (even after not having looked at it in a while).  It's a testament to good code for things to still be very usable a couple years out.  Retraining myself, cause even some older clojure repos (ring middleware, etc) can be very stable.

Despite whatever age of the navigation walkthrough, it was the simplest and most functional tutorial I'd seen and got up and started in no time.

Thanks again; been pretty busy, but if there's something straightforward I can do to help with documentation, examples, etc, lemme know
