### ISSUE TITLE
add a sortable table recipe

### ISSUE THREAD

**Issue by yogthos** [reagent-project/reagent-cookbook#8]

**Comment by JarrodCTaylor** [comment]
Not sure if it is what you had in mind with this, but I just created a pull request that adds a table that can be sorted by columns and filtered by content. Pull #16

**Comment by gadfly361** [comment]
@yogthos - @JarrodCTaylor just added a [sort-table](https://github.com/reagent-project/reagent-cookbook/tree/master/recipes/sort-table) recipe. Is this issue ok to close?

**Comment by yogthos** [comment]
looks great!
